// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/leftovers-2025/kds_backend/internal/kds/datasource"
	"github.com/leftovers-2025/kds_backend/internal/kds/handler"
	"github.com/leftovers-2025/kds_backend/internal/kds/repository/api"
	"github.com/leftovers-2025/kds_backend/internal/kds/repository/mysql"
	"github.com/leftovers-2025/kds_backend/internal/kds/service"
)

// Injectors from wire.go:

func InitHandlerSets() *HandlerSets {
	db := datasource.GetMySqlConnection()
	userRepository := mysql.NewMySqlUserRepository(db)
	userCommandService := service.NewUserCommandService(userRepository)
	googleApiClient := datasource.NewGoogleApiClient()
	googleRepository := api.NewApiGoogleRepository(googleApiClient)
	googleCommandService := service.NewGoogleCommandService(userCommandService, userRepository, googleRepository)
	googleHandler := handler.NewGoogleHandler(googleCommandService)
	handlerSets := &HandlerSets{
		GoogleHandler: googleHandler,
	}
	return handlerSets
}

// wire.go:

var datasourceSet = wire.NewSet(datasource.NewGoogleApiClient, datasource.GetMySqlConnection)

var repositorySet = wire.NewSet(api.NewApiGoogleRepository, mysql.NewMySqlUserRepository)

var serviceSet = wire.NewSet(service.NewUserCommandService, service.NewGoogleCommandService)

var handlerSet = wire.NewSet(handler.NewGoogleHandler)

type HandlerSets struct {
	GoogleHandler *handler.GoogleHandler
}
